name: Bug report
description: Report a defect in registry entries or validation tooling.
labels: ["models", "bug"]
body:
  - type: textarea
    id: what
    attributes:
      label: What happened?
      description: Describe the observed behavior.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What did you expect?
    validations:
      required: true

  - type: textarea
    id: affected
    attributes:
      label: Which files / model ids are affected?
      description: Provide paths and model ids/versions.
    validations:
      required: true
